#!/bin/bash

select choix in "push" "pull" "git clone" "status" "quitter"
do
	case $REPLY in
		1)	echo "Message du commit"
			read rep
			git config --global user.email victorien.denoyelle@epitech.eu
			git add -A
			git commit -m "$rep"
			git push
			echo -e "Push effectué\n";;
		2)	git pull 
			echo -e "pull effectué\n";;
		3)	echo "Répertoire à clone"
			read rep
			git clone $rep
			echo -e"clone effectué\n";;
		4)	git status;;
		5)	break;;
		*)	echo "Mauvaise entrée";;
	esac
done
